### ISSUE TITLE
no longer working.

### ISSUE THREAD

**Issue by eracer001** [cgmckeever/smartthings#5]
Any idea how to get this device working with the new updates to smartthings?

**Comment by cgmckeever** [comment]
which device? There are a few things baked into this repo. 
On a side note, most of this has been moved over to hubitat in one manner or another

**Comment by eracer001** [comment]
Sorry for putting this in the wrong spot... I'm trying to get the Osram Lightify Smart Dimming Switch to work, and as far as I can tell, this is the most recent device handler... But I'm not sure what to do at this point with all the changes.  I'm still using smartthings as my hub.

**Comment by cgmckeever** [comment]
ah, you mean for this switch?
https://community.smartthings.com/t/obsolete-faq-sylvania-battery-power-dimming-switch-model-73743-why-there-are-three-different-dths-to-choose-from/107714

unfortunately, Im not sure what the new smartthings eco-system looks like for device-handlers.

**Comment by eracer001** [comment]
Yes, thanks! I don't think you can add custom device handler's anymore...
Appreciate your response anyway though.

**Comment by cgmckeever** [comment]
Sorry I could not be more help
